#!/usr/bin/env sh

say() {
  printf '%s\n' "$1"
}

stp() {
  say "Stashing all your stuff, hang tight!"
  git add -A
  git stash

  say "Testing your code, lets hope it goes right."
  
  if rake ; then
    say "Looks like everything went OK... I think. Returning your code."
    git stash pop
  else
    say "My... my code... its... BAD!"
    say "You might want to look at what went wrong and remember to pop the stash!"
  fi
}

stp "$@"