#!/usr/bin/env sh

say() {
  printf '\n%s\n\n' "$1"
}

stp() {
  say "Stashing all your stuff, hang tight!"
  git add -A
  git stash

  say "Testing your code, lets hope it goes right."
  rake

  say "Looks like everything went OK... I think. Returning your code."
  git stash pop
}

stp "$@"